package com.uestc.fff.information.mapper;

import com.uestc.fff.information.domain.ExerciseInfo;
import com.uestc.fff.information.domain.ExerciseInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExerciseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    long countByExample(ExerciseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int deleteByExample(ExerciseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int deleteByPrimaryKey(String eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int insert(ExerciseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int insertSelective(ExerciseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    List<ExerciseInfo> selectByExample(ExerciseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    ExerciseInfo selectByPrimaryKey(String eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") ExerciseInfo record, @Param("example") ExerciseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int updateByExample(@Param("record") ExerciseInfo record, @Param("example") ExerciseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int updateByPrimaryKeySelective(ExerciseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int updateByPrimaryKey(ExerciseInfo record);
}