package com.uestc.fff.information.mapper;

import com.uestc.fff.information.domain.MateriasInfo;
import com.uestc.fff.information.domain.MateriasInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MateriasInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    long countByExample(MateriasInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int deleteByExample(MateriasInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int deleteByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int insert(MateriasInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int insertSelective(MateriasInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    List<MateriasInfo> selectByExample(MateriasInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    MateriasInfo selectByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") MateriasInfo record, @Param("example") MateriasInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int updateByExample(@Param("record") MateriasInfo record, @Param("example") MateriasInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int updateByPrimaryKeySelective(MateriasInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int updateByPrimaryKey(MateriasInfo record);
}