package com.uestc.fff.information.mapper;

import com.uestc.fff.information.domain.SchoolInfo;
import com.uestc.fff.information.domain.SchoolInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    long countByExample(SchoolInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int deleteByExample(SchoolInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int deleteByPrimaryKey(String scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int insert(SchoolInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int insertSelective(SchoolInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    List<SchoolInfo> selectByExample(SchoolInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    SchoolInfo selectByPrimaryKey(String scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") SchoolInfo record, @Param("example") SchoolInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int updateByExample(@Param("record") SchoolInfo record, @Param("example") SchoolInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int updateByPrimaryKeySelective(SchoolInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    int updateByPrimaryKey(SchoolInfo record);
}