package com.uestc.fff.information.mapper;

import com.uestc.fff.information.domain.TeachInfoExample;
import com.uestc.fff.information.domain.TeachInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeachInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    long countByExample(TeachInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int deleteByExample(TeachInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int deleteByPrimaryKey(TeachInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int insert(TeachInfoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int insertSelective(TeachInfoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    List<TeachInfoKey> selectByExample(TeachInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") TeachInfoKey record, @Param("example") TeachInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    int updateByExample(@Param("record") TeachInfoKey record, @Param("example") TeachInfoExample example);
}