package com.uestc.fff.information.domain;

public class ClassInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.Cid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.Cname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.Cinfo
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String cinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.Cid
     *
     * @return the value of class.Cid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.Cid
     *
     * @param cid the value for class.Cid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.Sc_id
     *
     * @return the value of class.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.Sc_id
     *
     * @param scId the value for class.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScId(String scId) {
        this.scId = scId == null ? null : scId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.Cname
     *
     * @return the value of class.Cname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.Cname
     *
     * @param cname the value for class.Cname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.Cinfo
     *
     * @return the value of class.Cinfo
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getCinfo() {
        return cinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.Cinfo
     *
     * @param cinfo the value for class.Cinfo
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setCinfo(String cinfo) {
        this.cinfo = cinfo == null ? null : cinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClassInfo other = (ClassInfo) that;
        return (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()))
            && (this.getScId() == null ? other.getScId() == null : this.getScId().equals(other.getScId()))
            && (this.getCname() == null ? other.getCname() == null : this.getCname().equals(other.getCname()))
            && (this.getCinfo() == null ? other.getCinfo() == null : this.getCinfo().equals(other.getCinfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        result = prime * result + ((getScId() == null) ? 0 : getScId().hashCode());
        result = prime * result + ((getCname() == null) ? 0 : getCname().hashCode());
        result = prime * result + ((getCinfo() == null) ? 0 : getCinfo().hashCode());
        return result;
    }
}