package com.uestc.fff.information.domain;

public class ExerciseInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.Eid
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.Cid
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.Ename
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.Einfo
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String einfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.Eresult
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String eresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.Eanswer
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String eanswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.Eid
     *
     * @return the value of exercise.Eid
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.Eid
     *
     * @param eid the value for exercise.Eid
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.Cid
     *
     * @return the value of exercise.Cid
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.Cid
     *
     * @param cid the value for exercise.Cid
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.Ename
     *
     * @return the value of exercise.Ename
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.Ename
     *
     * @param ename the value for exercise.Ename
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.Einfo
     *
     * @return the value of exercise.Einfo
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getEinfo() {
        return einfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.Einfo
     *
     * @param einfo the value for exercise.Einfo
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setEinfo(String einfo) {
        this.einfo = einfo == null ? null : einfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.Eresult
     *
     * @return the value of exercise.Eresult
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getEresult() {
        return eresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.Eresult
     *
     * @param eresult the value for exercise.Eresult
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setEresult(String eresult) {
        this.eresult = eresult == null ? null : eresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.Eanswer
     *
     * @return the value of exercise.Eanswer
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getEanswer() {
        return eanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.Eanswer
     *
     * @param eanswer the value for exercise.Eanswer
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setEanswer(String eanswer) {
        this.eanswer = eanswer == null ? null : eanswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ExerciseInfo other = (ExerciseInfo) that;
        return (this.getEid() == null ? other.getEid() == null : this.getEid().equals(other.getEid()))
            && (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()))
            && (this.getEname() == null ? other.getEname() == null : this.getEname().equals(other.getEname()))
            && (this.getEinfo() == null ? other.getEinfo() == null : this.getEinfo().equals(other.getEinfo()))
            && (this.getEresult() == null ? other.getEresult() == null : this.getEresult().equals(other.getEresult()))
            && (this.getEanswer() == null ? other.getEanswer() == null : this.getEanswer().equals(other.getEanswer()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEid() == null) ? 0 : getEid().hashCode());
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        result = prime * result + ((getEname() == null) ? 0 : getEname().hashCode());
        result = prime * result + ((getEinfo() == null) ? 0 : getEinfo().hashCode());
        result = prime * result + ((getEresult() == null) ? 0 : getEresult().hashCode());
        result = prime * result + ((getEanswer() == null) ? 0 : getEanswer().hashCode());
        return result;
    }
}