package com.uestc.fff.information.domain;

public class MajorInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.Mid
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.Sc_id
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.Mname
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String mname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.Minfo
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String minfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.Mid
     *
     * @return the value of major.Mid
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.Mid
     *
     * @param mid the value for major.Mid
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.Sc_id
     *
     * @return the value of major.Sc_id
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.Sc_id
     *
     * @param scId the value for major.Sc_id
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setScId(String scId) {
        this.scId = scId == null ? null : scId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.Mname
     *
     * @return the value of major.Mname
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.Mname
     *
     * @param mname the value for major.Mname
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.Minfo
     *
     * @return the value of major.Minfo
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getMinfo() {
        return minfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.Minfo
     *
     * @param minfo the value for major.Minfo
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setMinfo(String minfo) {
        this.minfo = minfo == null ? null : minfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MajorInfo other = (MajorInfo) that;
        return (this.getMid() == null ? other.getMid() == null : this.getMid().equals(other.getMid()))
            && (this.getScId() == null ? other.getScId() == null : this.getScId().equals(other.getScId()))
            && (this.getMname() == null ? other.getMname() == null : this.getMname().equals(other.getMname()))
            && (this.getMinfo() == null ? other.getMinfo() == null : this.getMinfo().equals(other.getMinfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMid() == null) ? 0 : getMid().hashCode());
        result = prime * result + ((getScId() == null) ? 0 : getScId().hashCode());
        result = prime * result + ((getMname() == null) ? 0 : getMname().hashCode());
        result = prime * result + ((getMinfo() == null) ? 0 : getMinfo().hashCode());
        return result;
    }
}