package com.uestc.fff.information.domain;

public class MateriasInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learningmaterials.Lid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learningmaterials.Cid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learningmaterials.Lname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String lname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learningmaterials.Material
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learningmaterials.PPT
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String ppt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learningmaterials.Video
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learningmaterials.Reference
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String reference;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learningmaterials.Lid
     *
     * @return the value of learningmaterials.Lid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learningmaterials.Lid
     *
     * @param lid the value for learningmaterials.Lid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setLid(String lid) {
        this.lid = lid == null ? null : lid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learningmaterials.Cid
     *
     * @return the value of learningmaterials.Cid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learningmaterials.Cid
     *
     * @param cid the value for learningmaterials.Cid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learningmaterials.Lname
     *
     * @return the value of learningmaterials.Lname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learningmaterials.Lname
     *
     * @param lname the value for learningmaterials.Lname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setLname(String lname) {
        this.lname = lname == null ? null : lname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learningmaterials.Material
     *
     * @return the value of learningmaterials.Material
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learningmaterials.Material
     *
     * @param material the value for learningmaterials.Material
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learningmaterials.PPT
     *
     * @return the value of learningmaterials.PPT
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getPpt() {
        return ppt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learningmaterials.PPT
     *
     * @param ppt the value for learningmaterials.PPT
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setPpt(String ppt) {
        this.ppt = ppt == null ? null : ppt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learningmaterials.Video
     *
     * @return the value of learningmaterials.Video
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learningmaterials.Video
     *
     * @param video the value for learningmaterials.Video
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learningmaterials.Reference
     *
     * @return the value of learningmaterials.Reference
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learningmaterials.Reference
     *
     * @param reference the value for learningmaterials.Reference
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setReference(String reference) {
        this.reference = reference == null ? null : reference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MateriasInfo other = (MateriasInfo) that;
        return (this.getLid() == null ? other.getLid() == null : this.getLid().equals(other.getLid()))
            && (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()))
            && (this.getLname() == null ? other.getLname() == null : this.getLname().equals(other.getLname()))
            && (this.getMaterial() == null ? other.getMaterial() == null : this.getMaterial().equals(other.getMaterial()))
            && (this.getPpt() == null ? other.getPpt() == null : this.getPpt().equals(other.getPpt()))
            && (this.getVideo() == null ? other.getVideo() == null : this.getVideo().equals(other.getVideo()))
            && (this.getReference() == null ? other.getReference() == null : this.getReference().equals(other.getReference()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learningmaterials
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLid() == null) ? 0 : getLid().hashCode());
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        result = prime * result + ((getLname() == null) ? 0 : getLname().hashCode());
        result = prime * result + ((getMaterial() == null) ? 0 : getMaterial().hashCode());
        result = prime * result + ((getPpt() == null) ? 0 : getPpt().hashCode());
        result = prime * result + ((getVideo() == null) ? 0 : getVideo().hashCode());
        result = prime * result + ((getReference() == null) ? 0 : getReference().hashCode());
        return result;
    }
}