package com.uestc.fff.information.domain;

import java.util.ArrayList;
import java.util.List;

public class SchoolInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public SchoolInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andScIdIsNull() {
            addCriterion("Sc_id is null");
            return (Criteria) this;
        }

        public Criteria andScIdIsNotNull() {
            addCriterion("Sc_id is not null");
            return (Criteria) this;
        }

        public Criteria andScIdEqualTo(String value) {
            addCriterion("Sc_id =", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotEqualTo(String value) {
            addCriterion("Sc_id <>", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThan(String value) {
            addCriterion("Sc_id >", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThanOrEqualTo(String value) {
            addCriterion("Sc_id >=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThan(String value) {
            addCriterion("Sc_id <", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThanOrEqualTo(String value) {
            addCriterion("Sc_id <=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLike(String value) {
            addCriterion("Sc_id like", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotLike(String value) {
            addCriterion("Sc_id not like", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdIn(List<String> values) {
            addCriterion("Sc_id in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotIn(List<String> values) {
            addCriterion("Sc_id not in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdBetween(String value1, String value2) {
            addCriterion("Sc_id between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotBetween(String value1, String value2) {
            addCriterion("Sc_id not between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScNameIsNull() {
            addCriterion("Sc_name is null");
            return (Criteria) this;
        }

        public Criteria andScNameIsNotNull() {
            addCriterion("Sc_name is not null");
            return (Criteria) this;
        }

        public Criteria andScNameEqualTo(String value) {
            addCriterion("Sc_name =", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotEqualTo(String value) {
            addCriterion("Sc_name <>", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameGreaterThan(String value) {
            addCriterion("Sc_name >", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameGreaterThanOrEqualTo(String value) {
            addCriterion("Sc_name >=", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameLessThan(String value) {
            addCriterion("Sc_name <", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameLessThanOrEqualTo(String value) {
            addCriterion("Sc_name <=", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameLike(String value) {
            addCriterion("Sc_name like", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotLike(String value) {
            addCriterion("Sc_name not like", value, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameIn(List<String> values) {
            addCriterion("Sc_name in", values, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotIn(List<String> values) {
            addCriterion("Sc_name not in", values, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameBetween(String value1, String value2) {
            addCriterion("Sc_name between", value1, value2, "scName");
            return (Criteria) this;
        }

        public Criteria andScNameNotBetween(String value1, String value2) {
            addCriterion("Sc_name not between", value1, value2, "scName");
            return (Criteria) this;
        }

        public Criteria andScAddIsNull() {
            addCriterion("Sc_add is null");
            return (Criteria) this;
        }

        public Criteria andScAddIsNotNull() {
            addCriterion("Sc_add is not null");
            return (Criteria) this;
        }

        public Criteria andScAddEqualTo(String value) {
            addCriterion("Sc_add =", value, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddNotEqualTo(String value) {
            addCriterion("Sc_add <>", value, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddGreaterThan(String value) {
            addCriterion("Sc_add >", value, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddGreaterThanOrEqualTo(String value) {
            addCriterion("Sc_add >=", value, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddLessThan(String value) {
            addCriterion("Sc_add <", value, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddLessThanOrEqualTo(String value) {
            addCriterion("Sc_add <=", value, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddLike(String value) {
            addCriterion("Sc_add like", value, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddNotLike(String value) {
            addCriterion("Sc_add not like", value, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddIn(List<String> values) {
            addCriterion("Sc_add in", values, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddNotIn(List<String> values) {
            addCriterion("Sc_add not in", values, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddBetween(String value1, String value2) {
            addCriterion("Sc_add between", value1, value2, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScAddNotBetween(String value1, String value2) {
            addCriterion("Sc_add not between", value1, value2, "scAdd");
            return (Criteria) this;
        }

        public Criteria andScWebIsNull() {
            addCriterion("Sc_web is null");
            return (Criteria) this;
        }

        public Criteria andScWebIsNotNull() {
            addCriterion("Sc_web is not null");
            return (Criteria) this;
        }

        public Criteria andScWebEqualTo(String value) {
            addCriterion("Sc_web =", value, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebNotEqualTo(String value) {
            addCriterion("Sc_web <>", value, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebGreaterThan(String value) {
            addCriterion("Sc_web >", value, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebGreaterThanOrEqualTo(String value) {
            addCriterion("Sc_web >=", value, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebLessThan(String value) {
            addCriterion("Sc_web <", value, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebLessThanOrEqualTo(String value) {
            addCriterion("Sc_web <=", value, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebLike(String value) {
            addCriterion("Sc_web like", value, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebNotLike(String value) {
            addCriterion("Sc_web not like", value, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebIn(List<String> values) {
            addCriterion("Sc_web in", values, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebNotIn(List<String> values) {
            addCriterion("Sc_web not in", values, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebBetween(String value1, String value2) {
            addCriterion("Sc_web between", value1, value2, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScWebNotBetween(String value1, String value2) {
            addCriterion("Sc_web not between", value1, value2, "scWeb");
            return (Criteria) this;
        }

        public Criteria andScPhoneIsNull() {
            addCriterion("Sc_phone is null");
            return (Criteria) this;
        }

        public Criteria andScPhoneIsNotNull() {
            addCriterion("Sc_phone is not null");
            return (Criteria) this;
        }

        public Criteria andScPhoneEqualTo(String value) {
            addCriterion("Sc_phone =", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneNotEqualTo(String value) {
            addCriterion("Sc_phone <>", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneGreaterThan(String value) {
            addCriterion("Sc_phone >", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("Sc_phone >=", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneLessThan(String value) {
            addCriterion("Sc_phone <", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneLessThanOrEqualTo(String value) {
            addCriterion("Sc_phone <=", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneLike(String value) {
            addCriterion("Sc_phone like", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneNotLike(String value) {
            addCriterion("Sc_phone not like", value, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneIn(List<String> values) {
            addCriterion("Sc_phone in", values, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneNotIn(List<String> values) {
            addCriterion("Sc_phone not in", values, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneBetween(String value1, String value2) {
            addCriterion("Sc_phone between", value1, value2, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScPhoneNotBetween(String value1, String value2) {
            addCriterion("Sc_phone not between", value1, value2, "scPhone");
            return (Criteria) this;
        }

        public Criteria andScInfoIsNull() {
            addCriterion("Sc_info is null");
            return (Criteria) this;
        }

        public Criteria andScInfoIsNotNull() {
            addCriterion("Sc_info is not null");
            return (Criteria) this;
        }

        public Criteria andScInfoEqualTo(String value) {
            addCriterion("Sc_info =", value, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoNotEqualTo(String value) {
            addCriterion("Sc_info <>", value, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoGreaterThan(String value) {
            addCriterion("Sc_info >", value, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoGreaterThanOrEqualTo(String value) {
            addCriterion("Sc_info >=", value, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoLessThan(String value) {
            addCriterion("Sc_info <", value, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoLessThanOrEqualTo(String value) {
            addCriterion("Sc_info <=", value, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoLike(String value) {
            addCriterion("Sc_info like", value, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoNotLike(String value) {
            addCriterion("Sc_info not like", value, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoIn(List<String> values) {
            addCriterion("Sc_info in", values, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoNotIn(List<String> values) {
            addCriterion("Sc_info not in", values, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoBetween(String value1, String value2) {
            addCriterion("Sc_info between", value1, value2, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScInfoNotBetween(String value1, String value2) {
            addCriterion("Sc_info not between", value1, value2, "scInfo");
            return (Criteria) this;
        }

        public Criteria andScPhoto1IsNull() {
            addCriterion("Sc_photo1 is null");
            return (Criteria) this;
        }

        public Criteria andScPhoto1IsNotNull() {
            addCriterion("Sc_photo1 is not null");
            return (Criteria) this;
        }

        public Criteria andScPhoto1EqualTo(String value) {
            addCriterion("Sc_photo1 =", value, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1NotEqualTo(String value) {
            addCriterion("Sc_photo1 <>", value, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1GreaterThan(String value) {
            addCriterion("Sc_photo1 >", value, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1GreaterThanOrEqualTo(String value) {
            addCriterion("Sc_photo1 >=", value, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1LessThan(String value) {
            addCriterion("Sc_photo1 <", value, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1LessThanOrEqualTo(String value) {
            addCriterion("Sc_photo1 <=", value, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1Like(String value) {
            addCriterion("Sc_photo1 like", value, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1NotLike(String value) {
            addCriterion("Sc_photo1 not like", value, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1In(List<String> values) {
            addCriterion("Sc_photo1 in", values, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1NotIn(List<String> values) {
            addCriterion("Sc_photo1 not in", values, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1Between(String value1, String value2) {
            addCriterion("Sc_photo1 between", value1, value2, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto1NotBetween(String value1, String value2) {
            addCriterion("Sc_photo1 not between", value1, value2, "scPhoto1");
            return (Criteria) this;
        }

        public Criteria andScPhoto2IsNull() {
            addCriterion("Sc_photo2 is null");
            return (Criteria) this;
        }

        public Criteria andScPhoto2IsNotNull() {
            addCriterion("Sc_photo2 is not null");
            return (Criteria) this;
        }

        public Criteria andScPhoto2EqualTo(String value) {
            addCriterion("Sc_photo2 =", value, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2NotEqualTo(String value) {
            addCriterion("Sc_photo2 <>", value, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2GreaterThan(String value) {
            addCriterion("Sc_photo2 >", value, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2GreaterThanOrEqualTo(String value) {
            addCriterion("Sc_photo2 >=", value, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2LessThan(String value) {
            addCriterion("Sc_photo2 <", value, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2LessThanOrEqualTo(String value) {
            addCriterion("Sc_photo2 <=", value, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2Like(String value) {
            addCriterion("Sc_photo2 like", value, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2NotLike(String value) {
            addCriterion("Sc_photo2 not like", value, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2In(List<String> values) {
            addCriterion("Sc_photo2 in", values, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2NotIn(List<String> values) {
            addCriterion("Sc_photo2 not in", values, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2Between(String value1, String value2) {
            addCriterion("Sc_photo2 between", value1, value2, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto2NotBetween(String value1, String value2) {
            addCriterion("Sc_photo2 not between", value1, value2, "scPhoto2");
            return (Criteria) this;
        }

        public Criteria andScPhoto3IsNull() {
            addCriterion("Sc_photo3 is null");
            return (Criteria) this;
        }

        public Criteria andScPhoto3IsNotNull() {
            addCriterion("Sc_photo3 is not null");
            return (Criteria) this;
        }

        public Criteria andScPhoto3EqualTo(String value) {
            addCriterion("Sc_photo3 =", value, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3NotEqualTo(String value) {
            addCriterion("Sc_photo3 <>", value, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3GreaterThan(String value) {
            addCriterion("Sc_photo3 >", value, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3GreaterThanOrEqualTo(String value) {
            addCriterion("Sc_photo3 >=", value, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3LessThan(String value) {
            addCriterion("Sc_photo3 <", value, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3LessThanOrEqualTo(String value) {
            addCriterion("Sc_photo3 <=", value, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3Like(String value) {
            addCriterion("Sc_photo3 like", value, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3NotLike(String value) {
            addCriterion("Sc_photo3 not like", value, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3In(List<String> values) {
            addCriterion("Sc_photo3 in", values, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3NotIn(List<String> values) {
            addCriterion("Sc_photo3 not in", values, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3Between(String value1, String value2) {
            addCriterion("Sc_photo3 between", value1, value2, "scPhoto3");
            return (Criteria) this;
        }

        public Criteria andScPhoto3NotBetween(String value1, String value2) {
            addCriterion("Sc_photo3 not between", value1, value2, "scPhoto3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 05 21:58:25 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}