package com.uestc.fff.information.domain;

public class SchoolInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_name
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_add
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scAdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_web
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scWeb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_phone
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_info
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_photo1
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scPhoto1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_photo2
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scPhoto2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_photo3
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scPhoto3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_id
     *
     * @return the value of school.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_id
     *
     * @param scId the value for school.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScId(String scId) {
        this.scId = scId == null ? null : scId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_name
     *
     * @return the value of school.Sc_name
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScName() {
        return scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_name
     *
     * @param scName the value for school.Sc_name
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScName(String scName) {
        this.scName = scName == null ? null : scName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_add
     *
     * @return the value of school.Sc_add
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScAdd() {
        return scAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_add
     *
     * @param scAdd the value for school.Sc_add
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScAdd(String scAdd) {
        this.scAdd = scAdd == null ? null : scAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_web
     *
     * @return the value of school.Sc_web
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScWeb() {
        return scWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_web
     *
     * @param scWeb the value for school.Sc_web
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScWeb(String scWeb) {
        this.scWeb = scWeb == null ? null : scWeb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_phone
     *
     * @return the value of school.Sc_phone
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScPhone() {
        return scPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_phone
     *
     * @param scPhone the value for school.Sc_phone
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScPhone(String scPhone) {
        this.scPhone = scPhone == null ? null : scPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_info
     *
     * @return the value of school.Sc_info
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScInfo() {
        return scInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_info
     *
     * @param scInfo the value for school.Sc_info
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScInfo(String scInfo) {
        this.scInfo = scInfo == null ? null : scInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_photo1
     *
     * @return the value of school.Sc_photo1
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScPhoto1() {
        return scPhoto1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_photo1
     *
     * @param scPhoto1 the value for school.Sc_photo1
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScPhoto1(String scPhoto1) {
        this.scPhoto1 = scPhoto1 == null ? null : scPhoto1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_photo2
     *
     * @return the value of school.Sc_photo2
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScPhoto2() {
        return scPhoto2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_photo2
     *
     * @param scPhoto2 the value for school.Sc_photo2
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScPhoto2(String scPhoto2) {
        this.scPhoto2 = scPhoto2 == null ? null : scPhoto2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_photo3
     *
     * @return the value of school.Sc_photo3
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScPhoto3() {
        return scPhoto3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_photo3
     *
     * @param scPhoto3 the value for school.Sc_photo3
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScPhoto3(String scPhoto3) {
        this.scPhoto3 = scPhoto3 == null ? null : scPhoto3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SchoolInfo other = (SchoolInfo) that;
        return (this.getScId() == null ? other.getScId() == null : this.getScId().equals(other.getScId()))
            && (this.getScName() == null ? other.getScName() == null : this.getScName().equals(other.getScName()))
            && (this.getScAdd() == null ? other.getScAdd() == null : this.getScAdd().equals(other.getScAdd()))
            && (this.getScWeb() == null ? other.getScWeb() == null : this.getScWeb().equals(other.getScWeb()))
            && (this.getScPhone() == null ? other.getScPhone() == null : this.getScPhone().equals(other.getScPhone()))
            && (this.getScInfo() == null ? other.getScInfo() == null : this.getScInfo().equals(other.getScInfo()))
            && (this.getScPhoto1() == null ? other.getScPhoto1() == null : this.getScPhoto1().equals(other.getScPhoto1()))
            && (this.getScPhoto2() == null ? other.getScPhoto2() == null : this.getScPhoto2().equals(other.getScPhoto2()))
            && (this.getScPhoto3() == null ? other.getScPhoto3() == null : this.getScPhoto3().equals(other.getScPhoto3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getScId() == null) ? 0 : getScId().hashCode());
        result = prime * result + ((getScName() == null) ? 0 : getScName().hashCode());
        result = prime * result + ((getScAdd() == null) ? 0 : getScAdd().hashCode());
        result = prime * result + ((getScWeb() == null) ? 0 : getScWeb().hashCode());
        result = prime * result + ((getScPhone() == null) ? 0 : getScPhone().hashCode());
        result = prime * result + ((getScInfo() == null) ? 0 : getScInfo().hashCode());
        result = prime * result + ((getScPhoto1() == null) ? 0 : getScPhoto1().hashCode());
        result = prime * result + ((getScPhoto2() == null) ? 0 : getScPhoto2().hashCode());
        result = prime * result + ((getScPhoto3() == null) ? 0 : getScPhoto3().hashCode());
        return result;
    }
}