package com.uestc.fff.information.domain;

public class SchoolInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_id
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_name
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String scName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_add
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String scAdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_phone
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String scPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.Sc_info
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    private String scInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_id
     *
     * @return the value of school.Sc_id
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_id
     *
     * @param scId the value for school.Sc_id
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setScId(String scId) {
        this.scId = scId == null ? null : scId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_name
     *
     * @return the value of school.Sc_name
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getScName() {
        return scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_name
     *
     * @param scName the value for school.Sc_name
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setScName(String scName) {
        this.scName = scName == null ? null : scName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_add
     *
     * @return the value of school.Sc_add
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getScAdd() {
        return scAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_add
     *
     * @param scAdd the value for school.Sc_add
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setScAdd(String scAdd) {
        this.scAdd = scAdd == null ? null : scAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_phone
     *
     * @return the value of school.Sc_phone
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getScPhone() {
        return scPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_phone
     *
     * @param scPhone the value for school.Sc_phone
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setScPhone(String scPhone) {
        this.scPhone = scPhone == null ? null : scPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.Sc_info
     *
     * @return the value of school.Sc_info
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public String getScInfo() {
        return scInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.Sc_info
     *
     * @param scInfo the value for school.Sc_info
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    public void setScInfo(String scInfo) {
        this.scInfo = scInfo == null ? null : scInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SchoolInfo other = (SchoolInfo) that;
        return (this.getScId() == null ? other.getScId() == null : this.getScId().equals(other.getScId()))
            && (this.getScName() == null ? other.getScName() == null : this.getScName().equals(other.getScName()))
            && (this.getScAdd() == null ? other.getScAdd() == null : this.getScAdd().equals(other.getScAdd()))
            && (this.getScPhone() == null ? other.getScPhone() == null : this.getScPhone().equals(other.getScPhone()))
            && (this.getScInfo() == null ? other.getScInfo() == null : this.getScInfo().equals(other.getScInfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jun 11 21:56:49 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getScId() == null) ? 0 : getScId().hashCode());
        result = prime * result + ((getScName() == null) ? 0 : getScName().hashCode());
        result = prime * result + ((getScAdd() == null) ? 0 : getScAdd().hashCode());
        result = prime * result + ((getScPhone() == null) ? 0 : getScPhone().hashCode());
        result = prime * result + ((getScInfo() == null) ? 0 : getScInfo().hashCode());
        return result;
    }
}