package com.uestc.fff.information.domain;

import java.util.Date;

public class StudentInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Mid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Smajor
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String smajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sphone
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String sphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sage
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String sage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Admission_time
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private Date admissionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sgrade
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String sgrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sid
     *
     * @return the value of student.Sid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sid
     *
     * @param sid the value for student.Sid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sc_id
     *
     * @return the value of student.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sc_id
     *
     * @param scId the value for student.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScId(String scId) {
        this.scId = scId == null ? null : scId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Mid
     *
     * @return the value of student.Mid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Mid
     *
     * @param mid the value for student.Mid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sname
     *
     * @return the value of student.Sname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sname
     *
     * @param sname the value for student.Sname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Smajor
     *
     * @return the value of student.Smajor
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getSmajor() {
        return smajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Smajor
     *
     * @param smajor the value for student.Smajor
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setSmajor(String smajor) {
        this.smajor = smajor == null ? null : smajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sphone
     *
     * @return the value of student.Sphone
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getSphone() {
        return sphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sphone
     *
     * @param sphone the value for student.Sphone
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setSphone(String sphone) {
        this.sphone = sphone == null ? null : sphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sage
     *
     * @return the value of student.Sage
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sage
     *
     * @param sage the value for student.Sage
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setSage(String sage) {
        this.sage = sage == null ? null : sage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Admission_time
     *
     * @return the value of student.Admission_time
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public Date getAdmissionTime() {
        return admissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Admission_time
     *
     * @param admissionTime the value for student.Admission_time
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setAdmissionTime(Date admissionTime) {
        this.admissionTime = admissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sgrade
     *
     * @return the value of student.Sgrade
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getSgrade() {
        return sgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sgrade
     *
     * @param sgrade the value for student.Sgrade
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setSgrade(String sgrade) {
        this.sgrade = sgrade == null ? null : sgrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StudentInfo other = (StudentInfo) that;
        return (this.getSid() == null ? other.getSid() == null : this.getSid().equals(other.getSid()))
            && (this.getScId() == null ? other.getScId() == null : this.getScId().equals(other.getScId()))
            && (this.getMid() == null ? other.getMid() == null : this.getMid().equals(other.getMid()))
            && (this.getSname() == null ? other.getSname() == null : this.getSname().equals(other.getSname()))
            && (this.getSmajor() == null ? other.getSmajor() == null : this.getSmajor().equals(other.getSmajor()))
            && (this.getSphone() == null ? other.getSphone() == null : this.getSphone().equals(other.getSphone()))
            && (this.getSage() == null ? other.getSage() == null : this.getSage().equals(other.getSage()))
            && (this.getAdmissionTime() == null ? other.getAdmissionTime() == null : this.getAdmissionTime().equals(other.getAdmissionTime()))
            && (this.getSgrade() == null ? other.getSgrade() == null : this.getSgrade().equals(other.getSgrade()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSid() == null) ? 0 : getSid().hashCode());
        result = prime * result + ((getScId() == null) ? 0 : getScId().hashCode());
        result = prime * result + ((getMid() == null) ? 0 : getMid().hashCode());
        result = prime * result + ((getSname() == null) ? 0 : getSname().hashCode());
        result = prime * result + ((getSmajor() == null) ? 0 : getSmajor().hashCode());
        result = prime * result + ((getSphone() == null) ? 0 : getSphone().hashCode());
        result = prime * result + ((getSage() == null) ? 0 : getSage().hashCode());
        result = prime * result + ((getAdmissionTime() == null) ? 0 : getAdmissionTime().hashCode());
        result = prime * result + ((getSgrade() == null) ? 0 : getSgrade().hashCode());
        return result;
    }
}