package com.uestc.fff.information.domain;

public class TeacherInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Mid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tage
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String tage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tphone
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String tphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tmajor
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String tmajor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tid
     *
     * @return the value of teacher.Tid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tid
     *
     * @param tid the value for teacher.Tid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Sc_id
     *
     * @return the value of teacher.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Sc_id
     *
     * @param scId the value for teacher.Sc_id
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setScId(String scId) {
        this.scId = scId == null ? null : scId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Mid
     *
     * @return the value of teacher.Mid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Mid
     *
     * @param mid the value for teacher.Mid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tname
     *
     * @return the value of teacher.Tname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tname
     *
     * @param tname the value for teacher.Tname
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tage
     *
     * @return the value of teacher.Tage
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getTage() {
        return tage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tage
     *
     * @param tage the value for teacher.Tage
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setTage(String tage) {
        this.tage = tage == null ? null : tage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tphone
     *
     * @return the value of teacher.Tphone
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getTphone() {
        return tphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tphone
     *
     * @param tphone the value for teacher.Tphone
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setTphone(String tphone) {
        this.tphone = tphone == null ? null : tphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tmajor
     *
     * @return the value of teacher.Tmajor
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getTmajor() {
        return tmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tmajor
     *
     * @param tmajor the value for teacher.Tmajor
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setTmajor(String tmajor) {
        this.tmajor = tmajor == null ? null : tmajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TeacherInfo other = (TeacherInfo) that;
        return (this.getTid() == null ? other.getTid() == null : this.getTid().equals(other.getTid()))
            && (this.getScId() == null ? other.getScId() == null : this.getScId().equals(other.getScId()))
            && (this.getMid() == null ? other.getMid() == null : this.getMid().equals(other.getMid()))
            && (this.getTname() == null ? other.getTname() == null : this.getTname().equals(other.getTname()))
            && (this.getTage() == null ? other.getTage() == null : this.getTage().equals(other.getTage()))
            && (this.getTphone() == null ? other.getTphone() == null : this.getTphone().equals(other.getTphone()))
            && (this.getTmajor() == null ? other.getTmajor() == null : this.getTmajor().equals(other.getTmajor()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTid() == null) ? 0 : getTid().hashCode());
        result = prime * result + ((getScId() == null) ? 0 : getScId().hashCode());
        result = prime * result + ((getMid() == null) ? 0 : getMid().hashCode());
        result = prime * result + ((getTname() == null) ? 0 : getTname().hashCode());
        result = prime * result + ((getTage() == null) ? 0 : getTage().hashCode());
        result = prime * result + ((getTphone() == null) ? 0 : getTphone().hashCode());
        result = prime * result + ((getTmajor() == null) ? 0 : getTmajor().hashCode());
        return result;
    }
}