package com.uestc.fff.information.domain;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Uid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String stid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SorT
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Uid
     *
     * @return the value of user.Uid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Uid
     *
     * @param uid the value for user.Uid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STid
     *
     * @return the value of user.STid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STid
     *
     * @param stid the value for user.STid
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setStid(String stid) {
        this.stid = stid == null ? null : stid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SorT
     *
     * @return the value of user.SorT
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SorT
     *
     * @param sort the value for user.SorT
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserInfo other = (UserInfo) that;
        return (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getStid() == null ? other.getStid() == null : this.getStid().equals(other.getStid()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Sep 05 21:58:25 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getStid() == null) ? 0 : getStid().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        return result;
    }
}