server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bsm?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #上传文件
    resources:
    static-locations: file:${file-path}
    #设置上传文件的大小
    servlet:
      multipart:
        max-file-size: 500MB
        max-request-size: 500MB
    file-path: F:\study\lab\bsm\src\main\resources\static\files
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html